[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_hello_world = "B1djBFNqSDoGUauSAfntHswvYMEtQiYRgt3RqbTtQw59"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arnoldsu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
